sudo: required

language: python

services:
  - docker

before_install:
- sudo apt-get update; sudo apt-get install python-selinux
- wget https://github.com/projectatomic/atomic/archive/v1.5.tar.gz
- tar -xzf v1.5.tar.gz
- cd atomic-1.5
- pip install pylint go-m2dman
- ln /usr/local/bin/pylint /usr/bin/pylint
- sudo pip install -r requirments.txt
- sudo make install
- cd ..


script:
- docker build -t helloapache helloapache
- mkdir helloapache-test; cd helloapache-test; atomic run helloapache
