sudo: required

language: python

services:
  - docker

before_install:
- wget https://github.com/projectatomic/atomic/archive/v1.5.tar.gz
- sudo python atomic-1.5/setup.py install


script:
- docker build -t helloapache helloapache
- atomic run helloapache
