sudo: required

language: python

services:
  - docker

before_install:
- sudo apt-get update; sudo apt-get install python-selinux
- wget https://github.com/projectatomic/atomic/archive/v1.5.tar.gz
- tar -xzf v1.5.tar.gz
- cd atomic-1.5
- sudo python setup.py install
- cd ..


script:
- helloapache/test.sh
